# Generated by Django 4.2.11 on 2024-04-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('images', models.TextField()),
                ('creationAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('slug', models.SlugField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='soko.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-creationAt',),
            },
        ),
    ]
